### ISSUE TITLE
filebeat.yml is not generated properly with multiline ansible_managed

### ISSUE THREAD

**Issue by qk4l** [DavidWittman/ansible-filebeat#6]
Hi,

Ansible 2.0  support multiline `ansible_managed` but  seems `to_yaml` filter does not correctly work in this case.

Example: 

```
cat /etc/filebeat/filebeat.yml 
# This file managed by Ansible.

Do not edit it manually.
All changes will be overwritten.
Thank you.

filebeat:
  prospectors:
  - document_type: apache
...
```

**Comment by DavidWittman** [comment]
@qk4l Thanks for reporting the issue. Can you provide me with the config to generate a multi-line `ansible_managed` for testing? I was unsuccessful in my attempts.

**Comment by DavidWittman** [comment]
Ah okay... Got it. You just need to prefix the second line with whitespace for it to interpret the newline. e.g.:

``` ini
[defaults]
ansible_managed = Ansible managed: {file}
 This is on another line
```

**Comment by DavidWittman** [comment]
I could change the template to read:

```
{{ ansible_managed|comment }}
```

But that would break 1.x compatibility, even if we use a conditional to test the Ansible version in the template. It looks like Ansible is compiling the template and will fail if any filters (like `comment`) don't exist. I think the solution here will either be removing `ansible_managed` from the config file (it has been hinted that `ansible_managed` will be deprecated in the future), or supply a separate template file for Ansible versions > 1.x.

With all that said, I suspect that using a multi-line `ansible_managed` config will cause issues in many different roles, so it's probably a best practice to just keep it on one line.

**Comment by qk4l** [comment]
@DavidWittman I'm sorry that I didn't check template and not wrote about `comment` filter. Actually I thought that it exist because some days ago added `comnent` filter to all my roles.

Luckily Ansible provide `ansible_version.major` variable so we can easy check if `comment` filter is supported.

**Comment by DavidWittman** [comment]
@qk4l Unfortunately (at least in my testing) even when you're checking the for Ansible 2.x, the template will fail on 1.x if the `comment` filter is used anywhere. :(

**Comment by qk4l** [comment]
@DavidWittman =( Ansible call `_get_filters()` for whole file and does not care if some of them will not be used. [Link to code](https://github.com/ansible/ansible/blob/stable-1.9/lib/ansible/utils/template.py#L242)

As workaround we can move logic to playbook but it'll require an additional template file and looks ugly.

**Comment by DavidWittman** [comment]
Oh nice... thanks for digging into that. I agree that using separate templates is ugly. Honestly, I think the right answer here is just to use single-line `ansible_managed` configurations. I'm going to close this, but if you absolutely must use multi-line managed statements I can look into using multiple templates.

At some point in the future I'll drop support for 1.x and this will be fixed then as well.
